behaviors:
  EnemyShipAgent:
    trainer_type: ppo
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    checkpoint_interval: 50000

environment_parameters:
  num_agents:
    curriculum:
      - name: TwoAgents
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2.0
        value: 2
      - name: FourAgents
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 4.0
        value: 4
      - name: EightAgents
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 12.0
        value: 8
      - name: TwelveAgents
        value: 12

  num_obstacles:
    curriculum:
      - name: NoObstacles
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 1.0
        value: 0
      - name: SomeObstacles
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 3.0
        value: 3
      - name: MoreObstacles
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 6.0
        value: 5
      - name: ManyObstacles
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 12.0
        value: 15
      - name: MaxObstacles
        value: 20

  arena_size:
    curriculum:
      - name: SmallArena
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 1.0
        value: 100
      - name: MediumArena
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 3.0
        value: 150
      - name: LargeArena
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 12.0
        value: 250
      - name: HugeArena
        value: 400

  aiming_reward:
    curriculum:
      - name: HighAimingReward
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2.0
        value: 2.0  # High aiming rewards initially
      - name: MediumAimingReward
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 10.0
        value: 1.0  # Medium aiming rewards
      - name: LowAimingReward
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 0.2  # Low aiming rewards
      - name: MinimalAimingReward
        value: 0.05  # Minimal aiming rewards for advanced lessons

  combat_focus:
    curriculum:
      - name: LowCombat
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2.0
        value: 0.5  # Low hit rewards initially
      - name: MediumCombat
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 10.0
        value: 1.0  # Medium hit rewards
      - name: HighCombat
        completion_criteria:
          measure: reward
          behavior: EnemyShipAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 30.0
        value: 2.0  # High hit rewards
      - name: MaxCombat
        value: 3.0  # Maximum hit rewards